"use client";

import { useState } from "react";
import { createUserWithEmailAndPassword, signOut } from "firebase/auth";
import { auth, db } from "@/lib/firebase/client";
import { doc, setDoc, serverTimestamp, writeBatch, collection } from "firebase/firestore";
import { Organization, UserProfile, Asset, AssetStatus, AssetType } from "@/types";
import { useAuth } from "@/contexts/AuthContext";

export default function PilotSetupPage() {
    const { user, logout } = useAuth();

    const [email, setEmail] = useState("");
    const [password, setPassword] = useState("TempPass123!"); // Default temp password
    const [companyName, setCompanyName] = useState("");
    const [displayName, setDisplayName] = useState("Manager");
    const [assetsJson, setAssetsJson] = useState<string>("");
    const [loading, setLoading] = useState(false);
    const [status, setStatus] = useState("");
    const [isConfirming, setIsConfirming] = useState(false);

    const generateDefaultAssets = () => {
        const assets = [];
        for (let i = 1; i <= 30; i++) {
            assets.push({
                qr_id: `uk_imk_${String(i).padStart(4, '0')}`,
                name: `Key ${String(i).padStart(2, '0')}`
            });
        }
        setAssetsJson(JSON.stringify(assets, null, 2));
    };

    const handleCreatePilot = async () => {
        if (!email || !companyName || !assetsJson) {
            alert("Please fill in all fields");
            return;
        }

        let parsedAssets: { qr_id: string; name: string }[] = [];
        try {
            parsedAssets = JSON.parse(assetsJson);
            if (!Array.isArray(parsedAssets)) throw new Error("Assets must be an array");
            if (parsedAssets.length > 30) {
                if (!confirm(`Warning: You are creating ${parsedAssets.length} assets. Standard limit is 30. Continue?`)) return;
            }
        } catch (e: any) {
            alert("Invalid JSON: " + e.message);
            return;
        }

        setLoading(true);
        setStatus("Initializing...");

        try {
            // 1. We must be logged out to create a new user via standard SDK 
            // OR use a secondary app instance. 
            // FOR SIMPLICITY: We will sign out the current admin.
            await signOut(auth);

            setStatus("Creating User...");
            const userCredential = await createUserWithEmailAndPassword(auth, email, password);
            const newUser = userCredential.user;

            setStatus("Creating Organization...");
            // Generate IDs
            const orgId = companyName.toLowerCase().replace(/[^a-z0-9]/g, '-') + '-' + Math.random().toString(36).substring(2, 7);

            // Create Organization Doc
            const orgRef = doc(db, "organizations", orgId);
            const newOrg: Organization = {
                id: orgId,
                name: companyName,
                subscriptionStatus: 'TRIAL',
                accountType: 'TRIAL_PILOT',
                createdAt: serverTimestamp() as any
            };
            await setDoc(orgRef, newOrg);

            setStatus("Creating Profile...");
            // Create User Profile
            const userRef = doc(db, "users", newUser.uid);
            const newProfile: UserProfile = {
                uid: newUser.uid,
                email: newUser.email!,
                displayName: displayName,
                orgId: orgId,
                role: 'ORG_ADMIN',
                joinedAt: serverTimestamp() as any
            };
            await setDoc(userRef, newProfile);

            setStatus("Batching Assets...");
            // Batch Create Assets
            const batch = writeBatch(db);
            const assetsCollection = collection(db, "assets");

            parsedAssets.forEach((item) => {
                const assetRef = doc(assetsCollection);
                const assetData: any = {
                    id: assetRef.id, // ID is auto-generated by doc() but we store it
                    orgId: orgId,
                    name: item.name,
                    type: AssetType.KEY,
                    status: AssetStatus.AVAILABLE,
                    qrCode: item.qr_id,
                    isSetupComplete: false, // FLAG FOR FIRST SCAN FLOW
                    createdAt: serverTimestamp(),
                    updatedAt: serverTimestamp(),
                    searchKeywords: [item.name.toLowerCase(), item.qr_id.toLowerCase()],
                    metaData: {
                        keyCode: item.qr_id // Legacy support
                    }
                };
                batch.set(assetRef, assetData);
            });

            await batch.commit();

            setStatus("Success! Please log in.");
            alert("Pilot Account Created Successfully. You are now logged in as the new user.");

            // Redirect or reload
            window.location.href = "/dashboard";

        } catch (error: any) {
            console.error(error);
            setStatus("Error: " + error.message);
            alert("Error: " + error.message);
            setLoading(false);
            // Attempt to re-login as previous user? Hard to do without creds.
        }
    };

    if (isConfirming) {
        return (
            <div className="p-8 max-w-2xl mx-auto">
                <h1 className="text-2xl font-bold mb-4 text-red-600">⚠ CAUTION</h1>
                <p className="mb-4">
                    Values: <br />
                    <strong>Email:</strong> {email} <br />
                    <strong>Org:</strong> {companyName} <br />
                    <strong>Assets:</strong> {JSON.parse(assetsJson || "[]").length} items
                </p>
                <p className="mb-6 font-bold">
                    This will log you out and create a new account immediately.
                </p>
                <div className="flex gap-4">
                    <button
                        onClick={() => setIsConfirming(false)}
                        className="px-4 py-2 border rounded"
                    >
                        Cancel
                    </button>
                    <button
                        onClick={handleCreatePilot}
                        disabled={loading}
                        className="px-4 py-2 bg-red-600 text-white rounded font-bold"
                    >
                        {loading ? status : "CONFIRM & CREATE"}
                    </button>
                </div>
            </div>
        );
    }

    return (
        <div className="p-8 max-w-4xl mx-auto">
            <h1 className="text-3xl font-bold mb-8">Pilot Account Generator</h1>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                <div className="space-y-4">
                    <div>
                        <label className="block text-sm font-medium mb-1">Company Name</label>
                        <input
                            className="w-full border p-2 rounded"
                            value={companyName}
                            onChange={e => setCompanyName(e.target.value)}
                            placeholder="e.g. Acme Lettings"
                        />
                    </div>

                    <div>
                        <label className="block text-sm font-medium mb-1">Admin Email</label>
                        <input
                            className="w-full border p-2 rounded"
                            value={email}
                            onChange={e => setEmail(e.target.value)}
                            placeholder="new.user@example.com"
                        />
                    </div>

                    <div>
                        <label className="block text-sm font-medium mb-1">Temp Password</label>
                        <input
                            className="w-full border p-2 rounded"
                            value={password}
                            onChange={e => setPassword(e.target.value)}
                        />
                    </div>
                </div>

                <div className="space-y-4">
                    <div>
                        <div className="flex justify-between mb-1">
                            <label className="block text-sm font-medium">Assets JSON (List of keys)</label>
                            <button onClick={generateDefaultAssets} className="text-xs text-blue-600 hover:underline">
                                Generate Default 30
                            </button>
                        </div>
                        <textarea
                            className="w-full border p-2 rounded font-mono text-xs h-64"
                            value={assetsJson}
                            onChange={e => setAssetsJson(e.target.value)}
                            placeholder='[{"qr_id": "...", "name": "..."}]'
                        />
                    </div>
                </div>
            </div>

            <div className="mt-8 border-t pt-8">
                <button
                    onClick={() => setIsConfirming(true)}
                    className="bg-blue-600 text-white px-6 py-3 rounded-lg font-bold hover:bg-blue-700 w-full md:w-auto"
                >
                    Review & Create Account
                </button>
            </div>
        </div>
    );
}
